include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  language:
    strict-raw-types: true

linter:
  rules:
    - cast_nullable_to_non_nullable
